name: cooktogether
description: "Une application de recettes de cuisine collaborative"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2"

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

workspace:
  - app
  - design_system
dependencies:
  google_ml_kit: ^0.20.0
