name: app
description: "Une application de recettes de cuisine collaborative"
publish_to: 'none'
version: 0.1.1
resolution: workspace

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.3
  firebase_performance: ^0.10.1+6
  firebase_crashlytics: ^4.3.6
  logger: ^2.5.0
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  mocktail: ^1.0.4

  design_system:
    path: ../design_system
  image_picker: ^1.1.2
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/